### PR TITLE
Cmac/migrate testapp androidx

### PR DESCRIPTION
**Pull request by colinmacdonald**
Migrating the example app to AndroidX. Resolved any breaking API and deprecation changes. Also had to update the Salesforce Mobile SDK version to the latest (7.0.0) to resolve AndroidX deprecations that existed in that dependency.

### CODE REVIEW

**Comment by colinmacdonald** [comment]
> Just one comment: are the spaces added to align with established practices or added automatically? @colinmacdonald

Yeah, need to confirm with @rileymacdonald-sf on what the style should be for this project. All the others are 2 space tabs rather than 4.

**Comment by rileymacdonald-sf** [comment]
Code style is checked into the project. Java is tab size/indent 4 and Kotlin is 2.

**Comment by colinmacdonald** [comment]
@rileymacdonald-sf Pushed the changes for the kotlin build variant. Looks like all the existing kotlin classes are actually using 4 space tabs for the project so that's what the formatting is here.

**Comment by plangstrom** [comment]
LGTM

**Pull request merged**
